language: c

sudo: required
env:
  global:
    - LUAROCKS=2.4.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=luajit     # latest stable version (2.0.5)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch
os:
  - linux

before_install:
  - openssl version
  - source .travis/setenv_lua.sh
  - bash .travis/setup_uv.sh
  - git submodule update --init --recursive
  - git submodule update --recursive

install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo $HOME/.lua/luarocks make openssl-scm-5.rockspec OPENSSL_DIR="/usr/local/opt/openssl"; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo $HOME/.lua/luarocks make openssl-scm-5.rockspec; fi'

script:
  - cd test
  - curl https://raw.githubusercontent.com/bluebird75/luaunit/master/luaunit.lua > luaunit.lua
  - lua test.lua
